#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry '[loopback]discovery_image_ocpaimanaged.iso' {
  set isofile='/boot/iso/discovery_image_ocpaimanaged.iso'
  loopback loop $isofile
}
